### PR TITLE
Updated default scope & authorization URL

### PR DESCRIPTION
**Pull request by suilillo**

### CODE REVIEW

**Comment by damianmarti** [comment]
Why this PR is not merged yet? 

The right url is auth.atlassian.com. 

accounts.atlassian.com is not working anymore.

**Comment by mrjoops** [comment]
Thank you for your contribution and sorry for being late, it's a bit weird but I only received the notification yesterday.

**Comment by naumanafzal0313** [comment]
hi, it is merged but when I install it, the old files are there, accounts.atlassian.com  is there.

**Comment by naumanafzal0313** [comment]
I think you haven't changed the version for the new files.

**Comment by naumanafzal0313** [comment]
the version 0.2.4 is from 2018 and url updating are in 2019, so can you please make a new version

**Pull request merged**
